[global]
excludes = [".git/**", "target/**"]

[formatter.rust]
command = "rustfmt"
options = ["--config-path", "./rustfmt.toml"]
includes = ["*.rs"]

[formatter.yaml]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]
