name: Nix flake check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**/*.nix"
      - "flake.lock"
      - ".github/workflows/flake-check.yaml"

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  flake-check:
    name: Flake Check
    uses: cffnpwr/actions/.github/workflows/flake-check.yaml@ffd3ff97e78cb13ea23152079f408427eb0ad20f # main
    permissions:
      contents: read
