name: Rust
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - "rustfmt.toml"
      - "flake.nix"
      - "flake.lock"
      - ".github/actions/setup-nix/**"
      - ".github/workflows/rust.yaml"

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  fmt:
    name: cargo fmt
    runs-on: macos-15
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: cargo fmt --check
        run: nix develop --command cargo fmt --check

  build:
    name: cargo build
    runs-on: macos-15
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: cargo build
        run: nix develop --command cargo build

  clippy:
    name: cargo clippy
    runs-on: macos-15
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: cargo clippy
        run: nix develop --command cargo clippy -- -D warnings
